# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d0285208f1a5dc3e622c9634a25c92be4421744d7454bc8a3cd01c9dbe0fdbb5fed9c1d3b31b2f2528638df59302dfffe61e8f3da90ff90d275766240bf6f91

test:
  secret_key_base: c6c7236bfb8049051c59f0ec09e20690ec4fdc564bdd165cbc5079b6827238e8260557d0815433c88dd186154f342cb3a0d05eb0c42ef0b09a4d6aea79f496ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
